[package]
name = "vtpm"
version = "0.1.0"
edition = "2021"

[features]
default = ["zeroize"]

# Enable use of unstable library feature 'allocator_api', enables
# graceful handling of memory allocation failures.
use_allocator_api = []

# Enable zeroization of sensitive memory contents when no longer needed.
zeroize = ["dep:zeroize"]

[dependencies]
zeroize = { version = "1.6.0", optional = true, default-features = false, features = ["alloc"] }
