[package]
name = "vtpm"
version = "0.1.0"
edition = "2021"

[features]
default = []

# Enable use of unstable library feature 'allocator_api', enables
# graceful handling of memory allocation failures.
use_allocator_api = []

[dependencies]
